### ISSUE TITLE
To be synchronized list keeps old values

### ISSUE THREAD

**Issue by nc4891** [CoreMedia/content-sync-example#11]
**Describe the bug**
Similar to https://github.com/CoreMedia/content-sync-example/issues/6
Same thing happens when only using the left panel

**To Reproduce**
1. select content A
2. select content B
3. deselect content A
4. deselect content B
5. select content A
6. check error: content B is appearing as well

**Expected behavior**
only content A must be selected

**Comment by cmfgi** [comment]
will have a look

**Comment by nc4891** [comment]
Hello @cmfgi, did you have a chance to check this problem?

**Comment by cmfgi** [comment]
Will fix it today
