### ISSUE TITLE
To see changes on remote systems, studio has to be restarted

### ISSUE THREAD

**Issue by blackappsolutions** [CoreMedia/content-sync-example#4]
**Bug-Description**
If one makes a change on a remote system while one has the "Content Sync" tool open, this change will never appear as long as the tool is running.

**To Reproduce**
* For example. You open op a folder on the remote system via "Content Sync".
* You see it is empty.
* You log in to this remote system via Studio
* You add a resource to this folder.
* Result: You never will see this resource in "Content Sync", even if you close end re-open the "Content Sync"-Window. You can resolve that only in re-loading studio itself, which is very time-consuming.

**Expected behavior**
Maybe a reload button would be nice?

**Comment by nc4891** [comment]
clarification: not a restart of studio server, but a studio browser refresh

**Comment by blackappsolutions** [comment]
@stefanpieper / @cmfgi: Could you give is some insights here?

**Comment by cmfgi** [comment]
There doesn't seem to be a timestamp by calling the rest-backend. Therefore the result is cached. Will add a change.

**Comment by cmfgi** [comment]
Will fix that issue

**Comment by cmfgi** [comment]
closed

**Comment by nc4891** [comment]
@cmfgi it is possible that you did not commit the file ReloadSourcePanelAction ?

**Comment by blackappsolutions** [comment]
@nchieffo Because it didn't compile?

**Comment by cmfgi** [comment]
fixed, my fault.
