### ISSUE TITLE
Content-Sync is keeping old state

### ISSUE THREAD

**Issue by blackappsolutions** [CoreMedia/content-sync-example#6]
**Bug Description**
see steps below

**To Reproduce**
1. Select two content items => observe right panel
2. De-select both
3. Select ONE of the previous selected ones again
4. Both are back - selected - on the right panel

Thanks to @ncieffo for finding this issue and making the screencast.

https://user-images.githubusercontent.com/3899967/118297361-5105b500-b4de-11eb-8329-9717f3ce6cfc.mp4

**Comment by cmfgi** [comment]
Will take care of that issue.

**Comment by cmfgi** [comment]
reference de-resolving is now working
